# Generated by Django 6.0.5 on 2026-05-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cui', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=12, null=True)),
                ('correo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre', models.CharField(max_length=15)),
                ('id_curso', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True)),
                ('docente', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotasAlumnosPorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.alumnos')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.curso')),
            ],
        ),
    ]
